config/routes.rb
Rails.application.routes.draw do
  post "/rate" => "rater#create", as: "rate"
  get "/users/:user_id/:type" => "relationships#index", as: :friendship
  devise_for :users

  root to: "books#index"

  resources :relationships, only: [:create, :destroy]
  resources :perusals, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :categories, only: [:index, :show]
  resources :requests, except: :show

  resources :users, except: :destroy do
    resource :favorites, only: [:edit, :show]
    resource :readings, except: [:new, :edit]
  end

  resources :books, except: [:new, :create, :destroy] do
    resources :reviews, except: [:index, :show, :new]
  end

  resources :reviews, only: [:create, :destroy] do
    resources :comments, only: [:create, :update, :destroy]
  end

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
    get "/signup" => "devise/registrations#new"
    get "/edit" => "devise/registrations#edit"
  end

  namespace :admin do
    resources :users, only: [:index, :show, :destroy]
    resources :categories
    resources :requests, only: [:index, :update, :destroy]
    resources :books do
      resources :reviews
    end

    resources :reviews do
      resources :comments
    end
    
    root to: "books#index"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @books = Book.all.paginate page: params[:page], per_page: Settings.per_page
  end
end

app/views/static_pages/home.html.erb
<% if user_signed_in?  %>
  <table class="table table-bordered">
    <% if current_user.following.blank? %>
      <%= render @books %>
    <% else %>
      <th><%= t :new_feed %></th>  
      <% current_user.following.each do |user| %>
        <% if user.activities.any? %>
          <tr>
            <td><%= link_to user.email, user_path(user) %></td>
          </tr>
          <% user.activities.each do |activity| %>
            <tr>
              <%= render activity, user: user %>
            </tr>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </table>  
<% else %>
  <div class="center jumbotron">
    <h1><%= t :welcome_to_app %></h1>
    <%= link_to t(:sign_up), signup_path, class: "btn btn-lg btn-primary" %>
  </div>  
<% end %>