config/routes.rb
Rails.application.routes.draw do
  post "/rate" => "rater#create", as: "rate"
  get "/users/:user_id/:type" => "relationships#index", as: :friendship
  devise_for :users

  root to: "books#index"

  resources :relationships, only: [:create, :destroy]
  resources :perusals, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :categories, only: [:index, :show]
  resources :requests, except: :show

  resources :users, except: :destroy do
    resource :favorites, only: [:edit, :show]
    resource :readings, except: [:new, :edit]
  end

  resources :books, except: [:new, :create, :destroy] do
    resources :reviews, except: [:index, :show, :new]
  end

  resources :reviews, only: [:create, :destroy] do
    resources :comments, only: [:create, :update, :destroy]
  end

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
    get "/signup" => "devise/registrations#new"
    get "/edit" => "devise/registrations#edit"
  end

  namespace :admin do
    resources :users, only: [:index, :show, :destroy]
    resources :categories
    resources :requests, only: [:index, :update, :destroy]
    resources :books do
      resources :reviews
    end

    resources :reviews do
      resources :comments
    end
    
    root to: "books#index"
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :category

  has_many :reviews, dependent: :destroy
  has_many :perusals, dependent: :destroy

  validates :title, presence: true

  scope :order_by_created_at, -> {order created_at: :DESC}
  scope :random_books, -> {limit(Settings.number_of_random_books).order("RANDOM()")}

  mount_uploader :picture, PictureUploader
  ratyrate_rateable Settings.rate.content, Settings.rate.design
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  load_and_authorize_resource
  before_action :verify_admin

  def index
    @books = @books.order_by_created_at
                   .paginate page: params[:page],
                             per_page: Settings.books_per_page
  end

  def show
    @reviews = Review.order_by_created_at
                     .paginate page: params[:page],
                               per_page: Settings.reviews_per_page
  end

  def new
    @categories = Category.all
  end

  def create
    respond_to do |format|
      if @book.save
        format.json {head :no_content}
        format.html {redirect_to admin_books_url}
        format.js
      else
        format.json {render json: @book.errors.full_messages,
                            status: :unprocessable_entity}
      end
    end
  end

  def edit
    @categories = Category.all
  end

  def update
    respond_to do |format|
      if @book.update! book_params
        format.json {head :no_content}
        format.html {redirect_to admin_books_url}
        format.js
      else
        format.json {render json: @book.errors.full_messages,
                            status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @book.destroy
    respond_to do |format|
      format.js
      format.html {redirect_to admin_books_url}
      format.json {head :no_content}
    end
  end

  private
  def book_params
    params.require(:book).permit :title, :author, :description, :picture, :category_id, :ISBN
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  load_and_authorize_resource

  def index
    @search = Book.search(params[:book_search], search_key: :book_search)
    
    @books = @search.result(distinct: true).order_by_created_at
               .paginate page: params[:page],
                         per_page: Settings.paginate.books_per_page
  end

  def show
    @reviews = @book.reviews.order_by_created_at
    @books = Book.random_books
  end
end

app/views/admin/books/_book.html.erb
<tr id="book_<%= book.id %>">
  <td><%= book.title %></td>
  <td><%= book.author %></td>
  <td><%= book.description %></td>
  <td><%= image_tag book.picture.url if book.picture? %></td>
  <td>
    <%= link_to t(:details), admin_book_path(book),
                             class: "btn btn-success" %>

    <%= link_to t(:edit), edit_admin_book_path(book), remote: true,
                          class: "btn btn-primary" %>

    <%= link_to t(:delete), admin_book_path(book), method: :delete,
                            remote: true, data: {confirm: t(:confirm)},
                            class: "btn btn-danger" %>
  </td>
</tr>

app/views/admin/books/_dialog.html.erb
<div class="modal fade" id="dialog" tabindex="-1" role="dialog" 
     aria-labelledby="myModalLabel" aria-hidden="true" 
     data-backdrop="static" data-keyboard="true">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title"></h3>
      </div>

      <div class="modal-body">
      </div>
      
    </div>
  </div>
</div>

app/views/admin/books/_form.html.erb
<%= form_for [:admin, @book], html: {multipart: true, role: "form"}, remote: true do |f| %>
  <div id="error_explanation" class="bg-danger text-danger">
  </div>

  <div class="row">
    <div class="col-sm-6">

      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :author %>
        <%= f.text_field :author, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :ISBN %>
        <%= f.text_area :ISBN, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :category_id %>
        <%= f.collection_select :category_id, @categories, :id, :name, include_blank: true %>
      </div>

      <div class="form-group">
        <%= f.label :picture %>
        <%= f.file_field :picture, accept: "image/jpeg,image/gif,image/png" %>
      </div>

      <div class="form-group">
        <%= f.submit @book.new_record? ? t(:create) : t(:update), class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/books/create.js.erb
$("#dialog").modal("toggle");
$("#books").append("<%= j render (@book) %>")

app/views/admin/books/destroy.js.erb
$("#book_<%= @book.id %>").fadeOut();

app/views/admin/books/edit.html.erb
<% provide :title, t(:update_book) %>
<h1><%= t :update_book %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/admin/books/edit.js.erb
$("#dialog h3").html("<i class='glyphicon glyphicon-pencil'></i> Edit Book");
 
$(".modal-body").html("<%= j render("form") %>");
 
$("#dialog").modal("show");
 
$("#dialog").on("shown.bs.modal", function() {
  $(".first_input").focus()
})

app/views/admin/books/index.html.erb
<div class="container">

  <h1><%= t :all_books %></h1>

  <div class="well">
    <%= link_to t(:new_book), new_admin_book_path, remote: true,
                              class: "btn btn-primary" %>
  </div>

  <%= will_paginate %>
  <table id class="table table-bordered table-striped">
    <thead>
    <tr>
      <th class="col-md-2"><%= t :title %></th>
      <th class="col-md-1"><%= t :author %></th>
      <th class="col-md-3"><%= t :description %></th>
      <th class="col-md-2"><%= t :cover %></th>
      <th class="col-md-3"><%= t :actions %></th>
    </tr>
    </thead>
    <tbody id="books">
      <%= render @books %>
    </tbody>
  </table>

  <%= render "dialog" %>
</div>

app/views/admin/books/new.html.erb
<% provide :title, t(:new_book) %>
<h1><%= t :new_book %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/admin/books/new.js.erb
$("#dialog h3").html("<i class='glyphicon glyphicon-plus'></i> Add New Book");
 
$(".modal-body").html("<%= j render("form") %>");
 
$("#dialog").modal("show");
 
$("#dialog").on("shown.bs.modal", function() {
  $(".first_input").focus()
})

app/views/admin/books/show.html.erb
<h1><%= t :book_info %></h1>
<table id class="table table-bordered table-striped">
  <thead>
  <tr>
    <th><%= t :title %></th>
    <th><%= t :author %></th>
    <th><%= t :ISBN %></th>
    <th><%= t :cover %></th>
    <th><%= t :description %></th>
  </tr>
  </thead>
  <tbody id="books">
    <tr id="book_<%= @book.id %>">
      <td><%= @book.title %></td>
      <td><%= @book.author %></td>
      <td><%= @book.ISBN %></td>
      <td><%= image_tag @book.picture.url if @book.picture? %></td>
      <td><%= @book.description %></td>
    </tr>
  </tbody>
</table>

<h1><%= t :all_reviews %></h1>
<hr/>

<ol class="reviews">
  <%= render @reviews %>
</ol>
<%= will_paginate @reviews %>

app/views/admin/books/update.js.erb
$("#dialog").modal("toggle");
$("#book_<%= @book.id %>").replaceWith("<%= j render (@book) %>")