config/routes.rb
Rails.application.routes.draw do
  post "/rate" => "rater#create", as: "rate"
  get "/users/:user_id/:type" => "relationships#index", as: :friendship
  devise_for :users

  root to: "books#index"

  resources :relationships, only: [:create, :destroy]
  resources :perusals, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :categories, only: [:index, :show]
  resources :requests, except: :show

  resources :users, except: :destroy do
    resource :favorites, only: [:edit, :show]
    resource :readings, except: [:new, :edit]
  end

  resources :books, except: [:new, :create, :destroy] do
    resources :reviews, except: [:index, :show, :new]
  end

  resources :reviews, only: [:create, :destroy] do
    resources :comments, only: [:create, :update, :destroy]
  end

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
    get "/signup" => "devise/registrations#new"
    get "/edit" => "devise/registrations#edit"
  end

  namespace :admin do
    resources :users, only: [:index, :show, :destroy]
    resources :categories
    resources :requests, only: [:index, :update, :destroy]
    resources :books do
      resources :reviews
    end

    resources :reviews do
      resources :comments
    end
    
    root to: "books#index"
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :books, dependent: :destroy

  validates :name, presence: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  load_and_authorize_resource

  def index
    @categories = @categories.paginate page: params[:page], per_page: Settings.per_page
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t :create
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t :update
      redirect_to admin_categories_path
    else
      render :edit
    end
  end

  def destroy
    if @category.destroy
      flash[:success] = t :delete
    else
      flash[:danger] = t :fail
    end
    redirect_to admin_categories_path
  end

  private
  def category_params
    params.require(:category).permit :name
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource
  
  def index
    @categories = @categories.paginate page: params[:page], per_page: Settings.per_page
  end

  def show
  end
end

app/views/categories/_category.html.erb
<tr>
  <td><%= category.id %></td>
  <td><%= category.name %></td>
</tr>

app/views/categories/index.html.erb
<div class="container">
  <div class="row">
    <h1><%= t :categories %></h1>    
    <p><%= link_to t(:add_new_category), new_admin_category_path, class: "btn btn-success" %></p>
    <table class="table table-bordered">
      <tr>
        <th><%= t :id %></th>
        <th><%= t :category_name %></th>
      </tr>
      <%= render @categories %>
    </table>
    <%= will_paginate %>
  </div>
</div>

app/views/categories/show.html.erb
<table class="table table-bordered">
  <tr>
    <th><%= t :id %></th>
    <th><%= t :category_name %></th>
  </tr>
  <%= render @category %>
</table>